name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      Select:
        description: "Terraform apply"
        required: true
        default: "apply"
        type: choice
        options:
          - "apply"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS 
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init 

    - name: Plan Terraform
      run: terraform plan

    - name: Apply Terraform
      run: terraform ${{ inputs.Select }} -var'instance_name="test"' -auto-approve
    - name: Terraform destroy
      run:  |
        sleep 100
        terraform destroy -auto-approve
