name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
        Select:
          description: 'Select terraform Destroy'
          required: true
          default: 'destroy'
          type: choice
          options:
          - "destroy"


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name : TerraformSetup
      uses : hashicorp/setup-terraform@v2
      with :
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name : Terraaform init
      run : terraform init
    - name : Terraform destoy
      run : terraform ${{ inputs.Select }} -auto-approve
#         run : terraform init
#         #terraform workspace select s3_destroy
#         run: terraform import -var 'access_key={{ secrets.AWS_ACCESS_KEY }}' -var 'secret_key={{ secrets.AWS_SECRET_KEY }}' <resource_type>.<resource_name> <id>
